[project]
name = "my-first-mcp-server"
version = "0.1.0"
description = "Leave Management System MCP Server for Claude Desktop using FastMCP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=1.3.0",
    "fastmcp>=2.0.0"
]
